apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: monitoring
type: Opaque
stringData:
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_TOKEN: oIuTpK7hqiG8Fi2oBV42OOZHqsQn4UwKeMTSx6u0PdGoS_4bxEmyZRKSaPTY3zxL5iRTxZxtkrt4fJn6AGZyhg==
